### ISSUE TITLE
Issue on docs4

### ISSUE THREAD

**Issue by Shirooo5** [hyperbeam/docs#37]
Path: /home/getting-started{
curl -X POST -H 'Authorization: Bearer <your-api-key>' \
    `https://engine.hyperbeam.com/v0/vm`
curl -X POST -H 'Authorization: Bearer <your-api-key>' \
    https://engine.hyperbeam.com/v0/vm #

**Comment by philipjscott** [comment]
Hello, can you please describe the issue you're facing?
